name: Release GitHub Actions

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the release'
        required: true
      script:
        description: 'Specify the build script to run'
        required: false
        default: 'npm run all'
      node_version:
        description: "Specify Node.js version (e.g., '18', '20', 'lts/*')"
        required: false
        default: '24'

permissions:
  contents: read

jobs:
  release:
    permissions:
      actions: read
      id-token: write
      contents: write

    uses: step-security/reusable-workflows/.github/workflows/actions_release.yaml@fix_Verify_cherry_pick-Logic
    with:
      tag: '${{ github.event.inputs.tag }}'
      script: '${{ github.event.inputs.script }}'
      node_version: '${{ github.event.inputs.node_version }}'
