name: Auto Cherry-Pick from Upstream

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Base branch to create the PR against'
        required: true
        default: 'main'
      script:
        description: 'Script to run after audit fix'
        required: false
        default: 'npm run all'
      mode:
        description: 'Run mode: cherry-pick or verify'
        required: false
        default: 'cherry-pick'
  pull_request:
    types: [opened, synchronize, labeled]

permissions:
  contents: write
  pull-requests: write
  packages: read
  issues: write

jobs:
  cherry-pick:
    uses: step-security/reusable-workflows/.github/workflows/auto_cherry_pick.yaml@feature/verify-cherry-pick
    with:
      original-owner: 'jkroepke'
      repo-name: 'setup-vals'
      base_branch: ${{ inputs.base_branch }}
      script: ${{ inputs.script || 'npm run all' }}
      mode:
        ${{ github.event_name == 'pull_request' &&
        contains(fromJson(toJson(github.event.pull_request.labels)).*.name,
        'review-required') && 'verify' || (github.event_name ==
        'workflow_dispatch' && inputs.mode || '') }}
